name: PSA Caucion Bot

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: .state
          key: state-cache

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt

      - run: python caucion_alerta.py
        env:
            CAPITAL_BASE: "38901078.37"
            TENORS: "1,7,14,30"
            THRESH_1D: "40.0"
            THRESH_7D: "43.0"
            THRESH_14D: "44.0"
            THRESH_30D: "45.0"
            PREMIUM_SPREAD: "3.0"
            SUPER_HIGH: "48.0"
            DAILY_HOUR: "10"
            DAYS_IN_YEAR: "365"
            DAYS_MONTH: "30"
            PAYDAY_N: "4"
            PAYDAY_REMIND_DAYS: "2"
# opcional:
# SALARY_TARGET: "1500000"

